# Generated by Django 3.0.7 on 2020-06-18 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Dusting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Cleaning Date')),
                ('method', models.CharField(choices=[('T', 'Tiny Fan'), ('F', 'Feather Duster'), ('M', 'Mico-Fiber Cloth')], default='T', max_length=1)),
                ('pop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Pop')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
